modLoader="javafml"
loaderVersion="[${fml},)"
license="The Apache License, Version 2.0"
issueTrackerURL="https://www.github.com/MelanX/DataTrader/issues/"

[[mods]]
modId="datatrader"
version="${version}"
displayName="DataTrader"
displayTest="MATCH_VERSION"
displayURL="www.curseforge.com/members/melanx/"
updateJSONURL="https://assets.melanx.de/updates/data-trader.json"
authors="MelanX"
description="""
Adds a trader to the game which can be customized by datapacks.
"""

[[dependencies.datatrader]]
    modId="forge"
    mandatory=true
    versionRange="[${forge},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.datatrader]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.datatrader]]
    modId="libx"
    mandatory=true
    versionRange="[1.19.3-4.3.0,)"
    ordering="NONE"
    side="BOTH"
